[2025-06-24T11:35:17.392+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ml_pipeline.model_evaluation manual__2025-06-24T11:34:07.375161+00:00 [queued]>
[2025-06-24T11:35:17.408+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ml_pipeline.model_evaluation manual__2025-06-24T11:34:07.375161+00:00 [queued]>
[2025-06-24T11:35:17.409+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-06-24T11:35:17.425+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): model_evaluation> on 2025-06-24 11:34:07.375161+00:00
[2025-06-24T11:35:17.431+0000] {standard_task_runner.py:60} INFO - Started process 392 to run task
[2025-06-24T11:35:17.434+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'ml_pipeline', 'model_evaluation', 'manual__2025-06-24T11:34:07.375161+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/ml_pipeline.py', '--cfg-path', '/tmp/tmpa51hh1f0']
[2025-06-24T11:35:17.438+0000] {standard_task_runner.py:88} INFO - Job 28: Subtask model_evaluation
[2025-06-24T11:35:17.521+0000] {task_command.py:423} INFO - Running <TaskInstance: ml_pipeline.model_evaluation manual__2025-06-24T11:34:07.375161+00:00 [running]> on host 0bd1facfd373
[2025-06-24T11:35:17.612+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='sarah' AIRFLOW_CTX_DAG_ID='ml_pipeline' AIRFLOW_CTX_TASK_ID='model_evaluation' AIRFLOW_CTX_EXECUTION_DATE='2025-06-24T11:34:07.375161+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-24T11:34:07.375161+00:00'
[2025-06-24T11:35:22.309+0000] {logging_mixin.py:188} INFO - ‚úÖ Subprocess stdout:
[2025-06-24T11:35:22.311+0000] {logging_mixin.py:188} INFO -  Evaluation completed. R2: 0.9951, MAE: 4.5064
[2025-06-24T11:35:22.311+0000] {logging_mixin.py:188} INFO - ‚úÖ Subprocess stderr:
[2025-06-24T11:35:22.312+0000] {logging_mixin.py:188} INFO -  2025-06-24 11:35:19,279 - evaluation.utils.common - INFO - YAML charg√© : /opt/***/project/config/config.yaml
2025-06-24 11:35:19,289 - evaluation.utils.common - INFO - YAML charg√© : /opt/***/project/config/params.yaml
2025-06-24 11:35:19,293 - evaluation.utils.common - INFO - R√©pertoire cr√©√© ou existant : /opt/***/project/evaluation
2025-06-24 11:35:20,984 - __main__ - INFO - Loaded processed data: /opt/***/project/data/processed/clean_data.csv (shape=(108060, 13))
2025-06-24 11:35:21,035 - __main__ - INFO - Loaded model: /opt/***/project/models/xgb_model.pkl
2025-06-24 11:35:21,082 - __main__ - INFO - Computed metrics: {'r2_score': 0.9950689371966661, 'mae': 4.506441840792982}
2025-06-24 11:35:21,086 - evaluation.utils.common - INFO - R√©pertoire cr√©√© ou existant : /opt/***/project/evaluation
2025-06-24 11:35:21,092 - evaluation.utils.common - INFO - JSON sauvegard√© : /opt/***/project/evaluation/scores.json
2025-06-24 11:35:21,092 - __main__ - INFO - Metrics saved to: /opt/***/project/evaluation/scores.json
2025/06/24 11:35:21 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet

2025-06-24 11:35:21,602 - __main__ - INFO - Metrics logged to MLflow.
2025/06/24 11:35:21 INFO mlflow.tracking._tracking_service.client: üèÉ View run likeable-wolf-137 at: https://dagshub.com/Gsasana/rakuten-mlops.mlflow/#/experiments/1/runs/fc30ac84127343eebf065d2a528099a7.
2025/06/24 11:35:21 INFO mlflow.tracking._tracking_service.client: üß™ View experiment at: https://dagshub.com/Gsasana/rakuten-mlops.mlflow/#/experiments/1.
[2025-06-24T11:35:22.314+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-06-24T11:35:22.329+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=ml_pipeline, task_id=model_evaluation, execution_date=20250624T113407, start_date=20250624T113517, end_date=20250624T113522
[2025-06-24T11:35:22.365+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-06-24T11:35:22.386+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
