[2025-06-24T10:38:01.008+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ml_pipeline.model_evaluation manual__2025-06-24T10:37:06.228648+00:00 [queued]>
[2025-06-24T10:38:01.018+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ml_pipeline.model_evaluation manual__2025-06-24T10:37:06.228648+00:00 [queued]>
[2025-06-24T10:38:01.019+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-06-24T10:38:01.031+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): model_evaluation> on 2025-06-24 10:37:06.228648+00:00
[2025-06-24T10:38:01.037+0000] {standard_task_runner.py:60} INFO - Started process 592 to run task
[2025-06-24T10:38:01.040+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'ml_pipeline', 'model_evaluation', 'manual__2025-06-24T10:37:06.228648+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/ml_pipeline.py', '--cfg-path', '/tmp/tmps3ir3m4a']
[2025-06-24T10:38:01.042+0000] {standard_task_runner.py:88} INFO - Job 21: Subtask model_evaluation
[2025-06-24T10:38:01.100+0000] {task_command.py:423} INFO - Running <TaskInstance: ml_pipeline.model_evaluation manual__2025-06-24T10:37:06.228648+00:00 [running]> on host 3a06eb83c721
[2025-06-24T10:38:01.181+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='sarah' AIRFLOW_CTX_DAG_ID='ml_pipeline' AIRFLOW_CTX_TASK_ID='model_evaluation' AIRFLOW_CTX_EXECUTION_DATE='2025-06-24T10:37:06.228648+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-24T10:37:06.228648+00:00'
[2025-06-24T10:38:02.950+0000] {logging_mixin.py:188} INFO - ❌ Subprocess failed!
[2025-06-24T10:38:02.952+0000] {logging_mixin.py:188} INFO - ⚠️ STDOUT:
[2025-06-24T10:38:02.953+0000] {logging_mixin.py:188} INFO -  
[2025-06-24T10:38:02.953+0000] {logging_mixin.py:188} INFO - ⚠️ STDERR:
[2025-06-24T10:38:02.954+0000] {logging_mixin.py:188} INFO -  Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/***/project/src/evaluation/components/evaluate.py", line 14, in <module>
    from evaluation.config.configuration import ConfigurationManager
  File "/opt/***/project/src/evaluation/config/configuration.py", line 5, in <module>
    from evaluation.utils.common import read_yaml, create_directories
  File "/opt/***/project/src/evaluation/utils/common.py", line 40, in <module>
    def create_directories(paths: list[Path]) -> None:
TypeError: 'type' object is not subscriptable
[2025-06-24T10:38:02.954+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ml_pipeline.py", line 57, in run_evaluation
    result = subprocess.run(
  File "/usr/local/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['python', '-m', 'evaluation.components.evaluate', '--config', '/opt/airflow/project/config/config.yaml', '--params', '/opt/airflow/project/config/params.yaml']' returned non-zero exit status 1.
[2025-06-24T10:38:02.975+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=ml_pipeline, task_id=model_evaluation, execution_date=20250624T103706, start_date=20250624T103801, end_date=20250624T103802
[2025-06-24T10:38:02.995+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 21 for task model_evaluation (Command '['python', '-m', 'evaluation.components.evaluate', '--config', '/opt/airflow/project/config/config.yaml', '--params', '/opt/airflow/project/config/params.yaml']' returned non-zero exit status 1.; 592)
[2025-06-24T10:38:03.025+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-06-24T10:38:03.051+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
