[2025-06-24T09:12:54.755+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ml_pipeline.model_training manual__2025-06-24T09:12:32+00:00 [queued]>
[2025-06-24T09:12:54.774+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ml_pipeline.model_training manual__2025-06-24T09:12:32+00:00 [queued]>
[2025-06-24T09:12:54.776+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-06-24T09:12:54.811+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): model_training> on 2025-06-24 09:12:32+00:00
[2025-06-24T09:12:54.822+0000] {standard_task_runner.py:60} INFO - Started process 249 to run task
[2025-06-24T09:12:54.831+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'ml_pipeline', 'model_training', 'manual__2025-06-24T09:12:32+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/ml_pipeline.py', '--cfg-path', '/tmp/tmpdwzed1i0']
[2025-06-24T09:12:54.836+0000] {standard_task_runner.py:88} INFO - Job 30: Subtask model_training
[2025-06-24T09:12:54.914+0000] {task_command.py:423} INFO - Running <TaskInstance: ml_pipeline.model_training manual__2025-06-24T09:12:32+00:00 [running]> on host 3a0dbc7a332e
[2025-06-24T09:12:55.018+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='sarah' AIRFLOW_CTX_DAG_ID='ml_pipeline' AIRFLOW_CTX_TASK_ID='model_training' AIRFLOW_CTX_EXECUTION_DATE='2025-06-24T09:12:32+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-24T09:12:32+00:00'
[2025-06-24T09:12:55.059+0000] {logging_mixin.py:188} INFO - ❌ Subprocess failed!
[2025-06-24T09:12:55.061+0000] {logging_mixin.py:188} INFO - ⚠️ STDOUT:
[2025-06-24T09:12:55.061+0000] {logging_mixin.py:188} INFO -  
[2025-06-24T09:12:55.062+0000] {logging_mixin.py:188} INFO - ⚠️ STDERR:
[2025-06-24T09:12:55.062+0000] {logging_mixin.py:188} INFO -  /usr/local/bin/python: Error while finding module specification for 'training.components.train' (ModuleNotFoundError: No module named 'training')
[2025-06-24T09:12:55.063+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ml_pipeline.py", line 32, in run_training
    result = subprocess.run(
  File "/usr/local/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['python', '-m', 'training.components.train', '--config', '/opt/airflow/project/config/config.yaml', '--params', '/opt/airflow/project/config/params.yaml']' returned non-zero exit status 1.
[2025-06-24T09:12:55.081+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=ml_pipeline, task_id=model_training, execution_date=20250624T091232, start_date=20250624T091254, end_date=20250624T091255
[2025-06-24T09:12:55.102+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 30 for task model_training (Command '['python', '-m', 'training.components.train', '--config', '/opt/airflow/project/config/config.yaml', '--params', '/opt/airflow/project/config/params.yaml']' returned non-zero exit status 1.; 249)
[2025-06-24T09:12:55.126+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-06-24T09:12:55.154+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
